# Generated by Django 5.0.4 on 2024-05-08 08:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0002_surveyquestion_remove_question_survey_surveyanswer_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="surveyanswer",
            table="Survey_Answer",
        ),
        migrations.AlterModelTable(
            name="surveyquestion",
            table="Survey_Question",
        ),
    ]
