# Generated by Django 5.0.4 on 2024-05-16 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0003_alter_surveyanswer_table_alter_surveyquestion_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("member_id", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "User",
            },
        ),
        migrations.RenameModel(
            old_name="SurveyAnswer",
            new_name="Answer",
        ),
        migrations.RenameModel(
            old_name="SurveyQuestion",
            new_name="Question",
        ),
        migrations.RenameField(
            model_name="answer",
            old_name="answer_choice",
            new_name="answer_content",
        ),
        migrations.RenameField(
            model_name="answer",
            old_name="survey",
            new_name="question",
        ),
        migrations.AlterModelTable(
            name="answer",
            table="Answer",
        ),
        migrations.AlterModelTable(
            name="question",
            table="Question",
        ),
    ]
